project:
  type: website

website:
  title: "Yeswanth Chitirala"
  favicon: "images/yeswath.jpg"
  page-footer:
    center: |
      [Contact Yeswanth Chitirala](mailto: Yeswanth.YeswanthChitirala@my.unt.edu)
    left: |
      Made with [Yeswanth Chitirala](https://quarto.org/)
    right: |
      [Github Code Repo](https://github.com)
    background: "#00ff00"
    
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: blog posts
      - href: resume.qmd
        text: Resume
        
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: vapor
    css: styles.css

editor: visual

